const colors = require("tailwindcss/colors");

module.exports = {
  mode: "jit",
  purge: {
    content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
    safelist: [
      "bg-gray-400",
      "bg-red-400",
      "bg-orange-400",
      "bg-amber-400",
      "bg-green-400",
      "bg-emerald-400",
      "bg-teal-400",
      "bg-cyan-400",
      "bg-sky-400",
      "bg-blue-400",
      "bg-indigo-400",
      "bg-violet-400",
      "bg-purple-400",
      "bg-fuchsia-400",
      "bg-pink-400",
      "bg-rose-400",
      "border-red-400",
      "border-emerald-400",
      "border-amber-400",
    ],
  },
  darkMode: "class", // or 'media' or 'class'
  theme: {
    extend: {
      backgroundColor: ["checked"],
      colors: {
        primary: "var(--primary-color)",
        "primary-50": "var(--primary-color-50)",
        "primary-100": "var(--primary-color-100)",
        "primary-200": "var(--primary-color-200)",
        "primary-300": "var(--primary-color-300)",
        "primary-400": "var(--primary-color-400)",
        "primary-500": "var(--primary-color-500)",
        "primary-600": "var(--primary-color-600)",
        "primary-700": "var(--primary-color-700)",
        "primary-800": "var(--primary-color-800)",
        "primary-900": "var(--primary-color-900)",
        "accent-400": "var(--accent-color-400)",
        "accent-500": "var(--accent-color-500)",
        "accent-weekend": "var(--weekend-color)",
        red: colors.red,
        orange: colors.orange,
        amber: colors.amber,
        green: colors.green,
        emerald: colors.emerald,
        teal: colors.teal,
        cyan: colors.cyan,
        sky: colors.sky,
        blue: colors.blue,
        indigo: colors.indigo,
        violet: colors.violet,
        purple: colors.purple,
        fuchsia: colors.fuchsia,
        pink: colors.pink,
        rose: colors.rose,
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
