import {
  BiAlarmExclamation,
  BiBasket,
  BiBasketball,
  BiBell,
  BiBook,
  BiBookmarks,
  BiBulb,
  BiCalendar,
  BiCamera,
  BiCheckCircle,
  BiCommentDetail,
  BiEnvelopeOpen,
  BiFile,
  BiHome,
  BiInfoCircle,
  BiJoystick,
  BiListUl,
  BiPaste,
  BiVideo,
  BiWorld,
} from "react-icons/bi";

export const userDataTemplate = {
  username: "Username",
  profileColor: "red",
  allColors: [
    "red",
    "orange",
    "amber",
    "green",
    "emerald",
    "teal",
    "cyan",
    "sky",
    "blue",
    "indigo",
    "violet",
    "purple",
    "fuchsia",
    "pink",
    "rose",
  ],
  allIcons: [
    <BiListUl />,
    <BiFile />,
    <BiBook />,
    <BiBasket />,
    <BiBasketball />,
    <BiBell />,
    <BiBookmarks />,
    <BiCalendar />,
    <BiBulb />,
    <BiCamera />,
    <BiCheckCircle />,
    <BiPaste />,
    <BiCommentDetail />,
    <BiEnvelopeOpen />,
    <BiHome />,
    <BiInfoCircle />,
    <BiJoystick />,
    <BiVideo />,
    <BiWorld />,
    <BiAlarmExclamation />,
  ],
};
