export const userSettingsTemplate = {
  darkMode: false,
  sidebarCollapsed: false,
  sidebarGreeting: true,
  sidebarCalendar: true,
  sidebarPomodoro: true,
  sidebarTasks: true,
  sidebarNotes: true,
  notificationShow: true,
  notificationTasks: true,
  notificationPomodoro: true,
  notificationEvent: true,
  remindersToday: true,
  remindersImportant: true,
  remindersStarred: true,
  remindersPinned: true,
  remindersAll: true,
  readingProgress: true,
  readingComplete: true,
  readingType: true,
  readingFavorite: true,
  readingAll: true,
};
